// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserManagement.Data;
using UserManagement.Data.Context;

#nullable disable

namespace UserManagement.Data.Migrations
{
    [DbContext(typeof(UserManagementDbContext))]
    partial class UserManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserManagement.Data.Entities.Log", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Logs");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ActionType = "AddUser",
                            Details = "Test text #12",
                            Timestamp = new DateTime(2025, 7, 18, 14, 23, 45, 123, DateTimeKind.Unspecified),
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            ActionType = "DeleteUser",
                            Details = "Test text #34",
                            Timestamp = new DateTime(2025, 7, 18, 9, 15, 30, 456, DateTimeKind.Unspecified),
                            UserId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            ActionType = "UpdateUser",
                            Details = "Test text #56",
                            Timestamp = new DateTime(2025, 7, 18, 22, 5, 12, 789, DateTimeKind.Unspecified),
                            UserId = 3L
                        },
                        new
                        {
                            Id = 4L,
                            ActionType = "ViewUser",
                            Details = "Test text #78",
                            Timestamp = new DateTime(2025, 7, 18, 6, 47, 59, 321, DateTimeKind.Unspecified),
                            UserId = 4L
                        },
                        new
                        {
                            Id = 5L,
                            ActionType = "DeleteUser",
                            Details = "Test text #90",
                            Timestamp = new DateTime(2025, 7, 18, 17, 33, 10, 654, DateTimeKind.Unspecified),
                            UserId = 5L
                        },
                        new
                        {
                            Id = 6L,
                            ActionType = "ViewUser",
                            Details = "Test text #21",
                            Timestamp = new DateTime(2025, 7, 18, 11, 12, 25, 987, DateTimeKind.Unspecified),
                            UserId = 6L
                        },
                        new
                        {
                            Id = 7L,
                            ActionType = "UpdateUser",
                            Details = "Test text #43",
                            Timestamp = new DateTime(2025, 7, 18, 19, 44, 38, 210, DateTimeKind.Unspecified),
                            UserId = 7L
                        },
                        new
                        {
                            Id = 8L,
                            ActionType = "DeleteUser",
                            Details = "Test text #65",
                            Timestamp = new DateTime(2025, 7, 18, 3, 29, 50, 333, DateTimeKind.Unspecified),
                            UserId = 8L
                        },
                        new
                        {
                            Id = 9L,
                            ActionType = "AddUser",
                            Details = "Test text #87",
                            Timestamp = new DateTime(2025, 7, 18, 15, 55, 5, 876, DateTimeKind.Unspecified),
                            UserId = 9L
                        },
                        new
                        {
                            Id = 10L,
                            ActionType = "UpdateUser",
                            Details = "Test text #11",
                            Timestamp = new DateTime(2025, 8, 17, 8, 8, 8, 888, DateTimeKind.Unspecified),
                            UserId = 10L
                        },
                        new
                        {
                            Id = 11L,
                            ActionType = "ViewUser",
                            Details = "Test text #22",
                            Timestamp = new DateTime(2025, 8, 17, 10, 22, 33, 111, DateTimeKind.Unspecified),
                            UserId = 1L
                        },
                        new
                        {
                            Id = 12L,
                            ActionType = "UpdateUser",
                            Details = "Test text #33",
                            Timestamp = new DateTime(2025, 8, 17, 12, 34, 56, 222, DateTimeKind.Unspecified),
                            UserId = 2L
                        },
                        new
                        {
                            Id = 13L,
                            ActionType = "AddUser",
                            Details = "Test text #44",
                            Timestamp = new DateTime(2025, 8, 17, 14, 46, 19, 333, DateTimeKind.Unspecified),
                            UserId = 3L
                        },
                        new
                        {
                            Id = 14L,
                            ActionType = "AddUser",
                            Details = "Test text #55",
                            Timestamp = new DateTime(2025, 8, 17, 16, 58, 42, 444, DateTimeKind.Unspecified),
                            UserId = 4L
                        },
                        new
                        {
                            Id = 15L,
                            ActionType = "AddUser",
                            Details = "Test text #66",
                            Timestamp = new DateTime(2025, 8, 17, 18, 10, 5, 555, DateTimeKind.Unspecified),
                            UserId = 5L
                        },
                        new
                        {
                            Id = 16L,
                            ActionType = "UpdateUser",
                            Details = "Test text #77",
                            Timestamp = new DateTime(2025, 8, 17, 20, 21, 28, 666, DateTimeKind.Unspecified),
                            UserId = 6L
                        },
                        new
                        {
                            Id = 17L,
                            ActionType = "ViewUser",
                            Details = "Test text #88",
                            Timestamp = new DateTime(2025, 8, 17, 22, 33, 51, 777, DateTimeKind.Unspecified),
                            UserId = 7L
                        },
                        new
                        {
                            Id = 18L,
                            ActionType = "AddUser",
                            Details = "Test text #99",
                            Timestamp = new DateTime(2025, 8, 17, 0, 45, 14, 888, DateTimeKind.Unspecified),
                            UserId = 8L
                        },
                        new
                        {
                            Id = 19L,
                            ActionType = "DeleteUser",
                            Details = "Test text #10",
                            Timestamp = new DateTime(2025, 8, 17, 2, 56, 37, 999, DateTimeKind.Unspecified),
                            UserId = 9L
                        },
                        new
                        {
                            Id = 20L,
                            ActionType = "DeleteUser",
                            Details = "Test text #20",
                            Timestamp = new DateTime(2025, 8, 17, 4, 8, 0, 101, DateTimeKind.Unspecified),
                            UserId = 10L
                        },
                        new
                        {
                            Id = 21L,
                            ActionType = "ViewUser",
                            Details = "Test text #30",
                            Timestamp = new DateTime(2025, 8, 27, 6, 19, 23, 202, DateTimeKind.Unspecified),
                            UserId = 1L
                        },
                        new
                        {
                            Id = 22L,
                            ActionType = "ViewUser",
                            Details = "Test text #40",
                            Timestamp = new DateTime(2025, 8, 27, 8, 30, 46, 303, DateTimeKind.Unspecified),
                            UserId = 2L
                        },
                        new
                        {
                            Id = 23L,
                            ActionType = "UpdateUser",
                            Details = "Test text #50",
                            Timestamp = new DateTime(2025, 8, 27, 10, 42, 9, 404, DateTimeKind.Unspecified),
                            UserId = 3L
                        },
                        new
                        {
                            Id = 24L,
                            ActionType = "AddUser",
                            Details = "Test text #60",
                            Timestamp = new DateTime(2025, 8, 27, 12, 53, 32, 505, DateTimeKind.Unspecified),
                            UserId = 4L
                        },
                        new
                        {
                            Id = 25L,
                            ActionType = "AddUser",
                            Details = "Test text #70",
                            Timestamp = new DateTime(2025, 8, 27, 14, 4, 55, 606, DateTimeKind.Unspecified),
                            UserId = 5L
                        },
                        new
                        {
                            Id = 26L,
                            ActionType = "AddUser",
                            Details = "Test text #80",
                            Timestamp = new DateTime(2025, 8, 27, 16, 16, 18, 707, DateTimeKind.Unspecified),
                            UserId = 6L
                        },
                        new
                        {
                            Id = 27L,
                            ActionType = "DeleteUser",
                            Details = "Test text #90",
                            Timestamp = new DateTime(2025, 8, 27, 18, 27, 41, 808, DateTimeKind.Unspecified),
                            UserId = 7L
                        },
                        new
                        {
                            Id = 28L,
                            ActionType = "ViewUser",
                            Details = "Test text #15",
                            Timestamp = new DateTime(2025, 8, 27, 20, 39, 4, 909, DateTimeKind.Unspecified),
                            UserId = 8L
                        },
                        new
                        {
                            Id = 29L,
                            ActionType = "ViewUser",
                            Details = "Test text #25",
                            Timestamp = new DateTime(2025, 8, 27, 22, 50, 27, 111, DateTimeKind.Unspecified),
                            UserId = 9L
                        },
                        new
                        {
                            Id = 30L,
                            ActionType = "ViewUser",
                            Details = "Test text #35",
                            Timestamp = new DateTime(2025, 8, 27, 1, 1, 50, 222, DateTimeKind.Unspecified),
                            UserId = 10L
                        },
                        new
                        {
                            Id = 31L,
                            ActionType = "AddUser",
                            Details = "Test text #45",
                            Timestamp = new DateTime(2025, 9, 1, 3, 13, 13, 333, DateTimeKind.Unspecified),
                            UserId = 1L
                        },
                        new
                        {
                            Id = 32L,
                            ActionType = "DeleteUser",
                            Details = "Test text #55",
                            Timestamp = new DateTime(2025, 9, 1, 5, 24, 36, 444, DateTimeKind.Unspecified),
                            UserId = 2L
                        },
                        new
                        {
                            Id = 33L,
                            ActionType = "UpdateUser",
                            Details = "Test text #65",
                            Timestamp = new DateTime(2025, 9, 1, 7, 35, 59, 555, DateTimeKind.Unspecified),
                            UserId = 3L
                        },
                        new
                        {
                            Id = 34L,
                            ActionType = "UpdateUser",
                            Details = "Test text #75",
                            Timestamp = new DateTime(2025, 9, 1, 4, 33, 22, 346, DateTimeKind.Unspecified),
                            UserId = 4L
                        },
                        new
                        {
                            Id = 35L,
                            ActionType = "DeleteUser",
                            Details = "Test text #85",
                            Timestamp = new DateTime(2025, 9, 1, 1, 22, 20, 653, DateTimeKind.Unspecified),
                            UserId = 5L
                        });
                });

            modelBuilder.Entity("UserManagement.Data.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Forename")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Email = "ploew@example.com",
                            Forename = "Peter",
                            IsActive = true,
                            Surname = "Loew"
                        },
                        new
                        {
                            Id = 2L,
                            Email = "bfgates@example.com",
                            Forename = "Benjamin Franklin",
                            IsActive = true,
                            Surname = "Gates"
                        },
                        new
                        {
                            Id = 3L,
                            Email = "ctroy@example.com",
                            Forename = "Castor",
                            IsActive = false,
                            Surname = "Troy"
                        },
                        new
                        {
                            Id = 4L,
                            Email = "mraines@example.com",
                            Forename = "Memphis",
                            IsActive = true,
                            Surname = "Raines"
                        },
                        new
                        {
                            Id = 5L,
                            Email = "sgodspeed@example.com",
                            Forename = "Stanley",
                            IsActive = true,
                            Surname = "Goodspeed"
                        },
                        new
                        {
                            Id = 6L,
                            Email = "himcdunnough@example.com",
                            Forename = "H.I.",
                            IsActive = true,
                            Surname = "McDunnough"
                        },
                        new
                        {
                            Id = 7L,
                            Email = "cpoe@example.com",
                            Forename = "Cameron",
                            IsActive = false,
                            Surname = "Poe"
                        },
                        new
                        {
                            Id = 8L,
                            Email = "emalus@example.com",
                            Forename = "Edward",
                            IsActive = false,
                            Surname = "Malus"
                        },
                        new
                        {
                            Id = 9L,
                            Email = "dmacready@example.com",
                            Forename = "Damon",
                            IsActive = false,
                            Surname = "Macready"
                        },
                        new
                        {
                            Id = 10L,
                            Email = "jblaze@example.com",
                            Forename = "Johnny",
                            IsActive = true,
                            Surname = "Blaze"
                        },
                        new
                        {
                            Id = 11L,
                            Email = "rfeld@example.com",
                            Forename = "Robin",
                            IsActive = true,
                            Surname = "Feld"
                        });
                });

            modelBuilder.Entity("UserManagement.Data.Entities.Log", b =>
                {
                    b.HasOne("UserManagement.Data.Entities.User", "User")
                        .WithMany("Logs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserManagement.Data.Entities.User", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
